In [1]:
import nltk
import pandas as pd
nltk.download_shell()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Downloader>  l

Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_eng Averaged Perceptron Tagger (JSON)
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] averaged_perceptron_tagger_rus Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] bcp47............... BCP-47 Language Tags
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.............. Chat-80 Data Files
  [ ] city_database....... City Database
  [ ] cmudict............. The Carnegie Mellon Pronouncing Dictionary (0.6)
  [ ] comparative_sentences Comparative Sentence Dataset

Hit Enter to continue:  q

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Downloader>  q

In [2]:
import pandas as pd

messages = [line.rstrip() for line in open('/home/oem/Downloads/archive (2)/spam.csv', encoding='utf-8', errors='ignore')]
print(len(messages))

5575

In [3]:
messages[0]

'v1,v2,,,'

In [4]:
for mess_no,message in enumerate(messages[:10]):
    print(mess_no,message)
    print("\n")

0 v1,v2,,,


1 ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,


2 ham,Ok lar... Joking wif u oni...,,,


3 spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,


4 ham,U dun say so early hor... U c already then say...,,,


5 ham,"Nah I don't think he goes to usf, he lives around here though",,,


6 spam,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, 1.50 to rcv",,,


7 ham,Even my brother is not like to speak with me. They treat me like aids patent.,,,


8 ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,


9 spam,WINNER!! As a valued network customer you have been selected to receivea 900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.,,,

In [5]:
import pandas as pd

In [30]:
messages = pd.read_csv(
    '/home/oem/Downloads/archive (2)/spam.csv',
    encoding='latin-1',
    
)

messages=messages.rename(columns={
    'v1':'label',
    'v2':'message'
})
messages=messages[["label","message"]]
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [31]:
import string
mess="Sample message! Notice: it has punctuation."
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [37]:
nopunc=[c for c in mess if c not in string.punctuation]
nopunc

['S',
 'a',
 'm',
 'p',
 'l',
 'e',
 ' ',
 'm',
 'e',
 's',
 's',
 'a',
 'g',
 'e',
 ' ',
 'N',
 'o',
 't',
 'i',
 'c',
 'e',
 ' ',
 'i',
 't',
 ' ',
 'h',
 'a',
 's',
 ' ',
 'p',
 'u',
 'n',
 'c',
 't',
 'u',
 'a',
 't',
 'i',
 'o',
 'n']

In [38]:
nopunc=''.join(nopunc)
nopunc

'Sample message Notice it has punctuation'

In [39]:
from nltk.corpus import stopwords

In [40]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/oem/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [41]:
nopunc.split()

['Sample', 'message', 'Notice', 'it', 'has', 'punctuation']

In [42]:
clean_mess=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [43]:
clean_mess

['Sample', 'message', 'Notice', 'punctuation']

In [45]:
def text_process(mess):
    nopunc=[char for char in mess if char not in string.punctuation]
    nopunc="".join(nopunc)
    return [word for word in nopunc.split() if word.lower() not in stopwords.words("english")]

In [47]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [48]:
messages['message'].head(5).apply(text_process)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: message, dtype: object

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [51]:
bow_transformer=CountVectorizer(analyzer=text_process).fit(messages['message'])
print(len(bow_transformer.vocabulary_))

11304

In [54]:
mess4=messages['message'][6]
print(mess4)

Even my brother is not like to speak with me. They treat me like aids patent.

In [57]:
bow4=bow_transformer.transform([mess4])
print(bow4)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 7 stored elements and shape (1, 11304)>
  Coords	Values
  (0, 1777)	1
  (0, 4512)	1
  (0, 5111)	1
  (0, 7698)	2
  (0, 8653)	1
  (0, 9860)	1
  (0, 10513)	1

In [59]:
bow_transformer.get_feature_names_out()[7800]

'lotta'

In [62]:
messages_bow=bow_transformer.transform(messages['message'])
print('shape of the Sparse Matrix:',messages['message'])

shape of the Sparse Matrix: 0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: message, Length: 5572, dtype: object

In [64]:
messages_bow.nnz

50193

In [68]:
from sklearn.feature_extraction.text import TfidfTransformer

In [69]:
tfidf_transformer=TfidfTransformer().fit(messages_bow) 
tfidf4=tfidf_transformer.transform(bow4) 
print(tfidf4)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (1, 11304)>
  Coords	Values
  (0, 1777)	0.33521441416639297
  (0, 4512)	0.43692878744892083
  (0, 5111)	0.3383712690711893
  (0, 7698)	0.4149098236609654
  (0, 8653)	0.43692878744892083
  (0, 9860)	0.32680848361658965
  (0, 10513)	0.33521441416639297

In [70]:
messages_tfidf = tfidf_transformer.transform(messages_bow) 
from sklearn.naive_bayes import MultinomialNB 
spam_detect_model=MultinomialNB().fit(messages_tfidf,messages['label'] ) 
all_pred = spam_detect_model.predict(messages_tfidf) 
all_pred

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'],
      shape=(5572,), dtype='<U4')

In [71]:
from sklearn.model_selection import train_test_split 
msg_train,msg_test,label_train,label_test = train_test_split(messages['message'],messages['label']) 
spam_detect_model=MultinomialNB().fit(messages_tfidf,messages['label'] ) 
predict = spam_detect_model.predict(messages_tfidf)
from sklearn.metrics import classification_report
print(classification_report(messages['label'],predict))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      4825
        spam       1.00      0.85      0.92       747

    accuracy                           0.98      5572
   macro avg       0.99      0.92      0.95      5572
weighted avg       0.98      0.98      0.98      5572

In [72]:
print(classification_report(messages['label'],predict))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      4825
        spam       1.00      0.85      0.92       747

    accuracy                           0.98      5572
   macro avg       0.99      0.92      0.95      5572
weighted avg       0.98      0.98      0.98      5572

In [85]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('bow', CountVectorizer(analyzer=text_process)),
    # strings to token integer

    ('tfidf', TfidfTransformer()),
    # integer counts to weighted TF-IDF score

    ('classifier', MultinomialNB()),
    # train on TF-IDF vectors w/ Naive Bayes
])

pipeline.fit(msg_train, label_train)

predictions = pipeline.predict(msg_test)

print(classification_report(label_test, predictions))

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98      1195
        spam       1.00      0.72      0.84       198

    accuracy                           0.96      1393
   macro avg       0.98      0.86      0.91      1393
weighted avg       0.96      0.96      0.96      1393

In [88]:
from sklearn.model_selection import train_test_split

msg_train, msg_test, label_train, label_test = train_test_split(
    messages['message'],
    messages['label'],
    test_size=0.2,
    random_state=42
)

print(len(msg_train), len(label_train))
print(len(msg_test), len(label_test))

4457 4457
1115 1115

In [89]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn import svm
from sklearn.metrics import classification_report

pipeline1 = Pipeline([
    ('bow', CountVectorizer(analyzer=text_process)),
    ('tfidf', TfidfTransformer()),
    ('classifier', svm.SVC(
        C=1.0,
        kernel='linear',
        degree=3,
        gamma='auto'
    ))
])

pipeline1.fit(msg_train, label_train)

predictions1 = pipeline1.predict(msg_test)

print(classification_report(label_test, predictions1))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       965
        spam       0.99      0.89      0.93       150

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115